* Overview
  This package provides:
  - Automatic recognition and highlighting of things at point.
  - An interface for writing commands that operate on things.
  - Commands for copying, killing and pasting things as an example of use of this interface.
  - An option to disable the highlighting as soon as the user starts typing. It will be enabled again when the user calls any command apart from *self-insert-command*.
  Inspired by xah-fly-keys, expand-region and objed.
  Works best when combined with modal text editing.
  This package is not stable yet. It's sitll in development, public interface may change.

* Motivation
  I started working on this package because I was lookig for a new approach that would
  save me a couple of keystrokes on each common task such as copying and pasting text,
  evaluation of lisp expressions and shell-commands, changing letter case, etc.

  For a year I used a wonderful package "expand-region" for that purpose. Despite it being
  very smart and useful, it still requires 2 actions to select an object under the point.
  First, the user must navigate to the desired location, and then call er/expand-region
  to select an object. I thought that the second step was redundant and decided to
  write a package that works without it.

* Goals
  - Deterministic and unambiguous mechanism for identification and highlighting of things at point.
  - Modular design. This is a component that can be used to augment capabilities of other text
    editing packages and modal editing modes, rather than a complete mode. However, it can be used separately.
  - Lean codebase. This package will remain as small as possible.
  - A mechanism that allows existing commands to operate on highlighted things.
  - Simple interface for writing new commands that operate on highlighted things.

* Integration with expand region
  This is trivial. Add *er/expand-region* to *atp-known-repeatable-commands*. Now, when
  you call *er/expand-region* by issuing a keystroke, the highlighted thing will be marked
  as a region and then *er/expand-region* will execute, expanding this region.
  
  #+begin_src elisp
	(add-to-list 'atp-known-repeatable-commands 'er/expand-region)
  #+end_src

* Tasks
  - Use *defcustom* instead of *defvar* where possible.
  - Record a video demo.
  - Fix atp-toggle-comment.
  - Compatibility with electric-pair. (hard)
    Implement convenient insertion of pairs around highlighted thing.
